### ISSUE TITLE
installation unclear

### ISSUE THREAD

**Issue by poohsen** [Lord-Kamina/SwiftDefaultApps#10]
Maybe because I don't know this RCDefaultApp thing this is replacing. Where is the .prefpane i need to double-click? I don't have that locally and it's not in the repo either

**Comment by Lord-Kamina** [comment]
You get it from "Releases". The repo is just storage for the code and the files needed in case somebody wants to compile it themselves.

**Comment by rgbink** [comment]
OK. Where's *"Releases"*?

**Comment by Lord-Kamina** [comment]
![74a6e295-fce7-4c36-badb-a7d0adbad058](https://user-images.githubusercontent.com/6446892/53651340-36a8cf00-3c25-11e9-955f-f147d89c23e0.jpeg)

**Comment by rgbink** [comment]
👍
