### ISSUE TITLE
Setting default email client and browser presents Illegal instruction: 4

### ISSUE THREAD

**Issue by apizz** [Lord-Kamina/SwiftDefaultApps#13]
(BTW, this is awesome) Using the swda CLI tool.

Following the usage guide for `setHandler` - `swda setHandler <application> <type> [options] `- I am running the following commands to set the default email client & the default browser.

`swda setHandler --app /Applications/Microsoft\ Outlook.app --email`
`swda setHandler --app /Applications/Google\ Chrome.app --browser`

In both cases, the result is "Illegal instruction: 4".  In the case of the browser, however, this does produce the prompt to select the alternative browser or keep the current option.

I've tried changing the order of the parameters but I can't seem to get this to work using `--email` or `--browser`.  Was trying to use what appeared to be a simpler option for configuring this, rather than `--UTI`.

Am I missing something obvious when using `setHander` with `--email` & `--browser`??

**Comment by Lord-Kamina** [comment]
I'll check it out and get back to you.

**Comment by apizz** [comment]
@Lord-Kamina here it is!
[swda_2019-07-24-124042.crash.zip](https://github.com/Lord-Kamina/SwiftDefaultApps/files/3427886/swda_2019-07-24-124042.crash.zip)

**Comment by Lord-Kamina** [comment]
I've already found and fixed the bug; will try to release the fix during the weekend.

**Comment by Lord-Kamina** [comment]
86d6666 should fix this now. @apizz

**Comment by apizz** [comment]
@Lord-Kamina I can confirm with 2.0.1 I do not get the error message when setting either default browser or default email client.

Thanks!
