### ISSUE TITLE
Delay in collecting updated UTIs after setting?

### ISSUE THREAD

**Issue by apizz** [Lord-Kamina/SwiftDefaultApps#16]
What I ran `swda setHandler --UTI public.comma-separated-values-text --app "Microsoft Excel"` it says it completes successfully .  However, when I run a `swda getUTIs` immediately afterward it still shows the initial default app (Numbers) as the default.  That being said, when the CSV is opened it does use the correct the correct app.  After running `swda getUTIs` 10-15 seconds later it does show Excel as the default app.

Thinking that there is some timing / caching of UTIs that only acknowledges the change after 10 - 15 seconds?

Not sure if this is so much an issue as that I'm trying to script collecting the UTIs after making the change in order to verify it's set correctly.

**Comment by Lord-Kamina** [comment]
With the prefpane there _might_ be some caching but if you're using the CLI, then that's probably just what it takes for the LaunchServices database to update.

**Comment by apizz** [comment]
In this case only using the CLI.

Tried `sdwa setHandler --UTI public.comma-separated-values-text --app "Microsoft Excel.app"` and then `sdwa getHandler --UTI public.comma-separated-values-text` and still took roughly the same amount of time to ultimately return the updated app.

**Comment by Lord-Kamina** [comment]
In that case it's likely a limitation on the LaunchServices api.

**Comment by apizz** [comment]
OK, good to know.  Something just to be aware of I guess.
