### ISSUE TITLE
OMG AWESOME APP BEST EVER

### ISSUE THREAD

**Issue by simPod** [Lord-Kamina/SwiftDefaultApps#17]
MAN, THIS IS LIKE LITERARY 🔝 👌 APP OUT THERE. THERE'S NO OTHER EASY AND CLEAN WAY HOW TO HANDLE CUSTOM PROTOCOLS WITH DIGNITY IN MACOS.

MANY THANKS!!!

**Comment by simPod** [comment]
_and sorry for spam, couldn't hide the excitement_

**Comment by Lord-Kamina** [comment]
Hahaha it’s fine. In fact, issues with custom schemes is the reason I initially decided to make this.
