### ISSUE TITLE
No longer working on 10.14 Mojave

### ISSUE THREAD

**Issue by Einkoro** [Lord-Kamina/SwiftDefaultApps#6]
Attempting to open the v1.1.1 prefpane results in: 
```
You can’t open SwiftDefaultApps preferences pane because it doesn’t work on an Intel-based Mac.
```

ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391

**Comment by Lord-Kamina** [comment]
Yay apple. I haven't installed mojave yet so I can't test it for now. Will get back to you when I do.

**Comment by axelburks** [comment]
I have encountered the same problem.

**Comment by NuckChorris** [comment]
Looks like Apple broke Swift-based prefpanes — I'm trying to build one myself and getting the same error

**Comment by Lord-Kamina** [comment]
@nuckchorris they were broken in HS until 10.13.3 or so... Since I haven't yet installed Mojave I don't know what the actual error behind that message is, though.

Something you can try is to run the prefpane from terminal (as a parameter to System Preferences.app or whatever that's called), and pipe stderr to stdout. That should give you a slightly more verbose description of the actual error.

**Comment by NuckChorris** [comment]
Thanks for that tip! Here's what I'm getting when I run from the terminal:

```
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/emma/Library/PreferencePanes/SwiftDefaultApps.prefPane/Contents/MacOS/SwiftDefaultApps being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/emma/Library/PreferencePanes/SwiftDefaultApps.prefPane/Contents/MacOS/SwiftDefaultApps being ignored in restricted program because of @executable_path
2018-10-02 13:52:09.555 System Preferences[5752:346914] [NSPrefPaneBundle instantiatePrefPaneObject] (/Users/emma/Library/PreferencePanes/SwiftDefaultApps.prefPane): principalClass is nil.
```

Hopefully this isn't a regression to the High Sierra bug

**Comment by Lord-Kamina** [comment]
Definitely isn't a regression. Seems like a new security restriction is breaking it. Hopefully won't be too hard to fix. Maybe look in the developer docs what they say about using @executable_path (most likely it is deprecated in favor of @rpath or something like that)

**Comment by Lord-Kamina** [comment]
Please check whether https://github.com/Lord-Kamina/SwiftDefaultApps/releases/tag/v1.1.2 fixes it?

**Comment by Lord-Kamina** [comment]
> That fixed it for me on 10.14. 

Great!

> Text label in prefs overlaps the next icon a bit though:

Don't see how I could fix that, short of changing the app's name.

**Comment by Einkoro** [comment]
Pretty minor anyway. If you put spaces in do titles even wrap to a new line or truncate?

**Comment by ajasperhh** [comment]
@Lord-Kamina This tool is very helpful. But the CLI doesn't work, is this possible?

**Comment by Lord-Kamina** [comment]
@ajasperhh it's certainly *possible*. The command-line though is just a different front-end for the same functions that drive the prefpane, though.

**Comment by ajasperhh** [comment]
Excuse me, but then I'm too stupid. Can you please tell me how to use it? maybe a terminal command? and of course we will have a beer together :-)

Am 11.03.2019 um 18:41 schrieb Gregorio Litenstein <notifications@github.com>:

@ajasperhh <https://github.com/ajasperhh> it's certainly possible. The command-line though is just a different front-end for the same functions that drive the prefpane, though.

**Comment by Lord-Kamina** [comment]
@ajasperhh It's my bad, it seems. The release archive does not include the CLI version, so you'd have to build it yourself. I'll have to correct that but cannot do it today.
