### ISSUE TITLE
[FR] use more vertical space on the settings app

### ISSUE THREAD

**Issue by andrewcrook** [Lord-Kamina/SwiftDefaultApps#82]
The new settings.app has more vertical space. 

I wonder if the controls could use more of that space?

Is it possible to make the pain auto adjust when the settings app is resized?

**Comment by Lord-Kamina** [comment]
Not really, because I'm looking into just dropping the preference pane altogether, and turning it into a standalone SwiftUI app instead.

**Comment by andrewcrook** [comment]
> Not really, because I'm looking into just dropping the preference pane altogether, and turning it into a standalone SwiftUI app instead.

oh I didn’t know that. Sounds like a better solution
