### ISSUE TITLE
Can't add custom URL scheme

### ISSUE THREAD

**Issue by Woundorf** [Lord-Kamina/SwiftDefaultApps#9]
Hi, I want to add a custom URL scheme, which from the README I understood is possible, but when I try it, it shows me this error:

![imatge](https://user-images.githubusercontent.com/1915151/51379747-6934b780-1b10-11e9-86d6-ded2be317167.png)

Edit: I tried it with 10.13.6.

**Comment by Lord-Kamina** [comment]
Hmm that's new... Can you check inside the prefpane bundle and see if ThisAppDoesNothing.app is there? By default, new schemes are assigned to it; it seems like it's failing to find that app.

**Comment by Woundorf** [comment]
Yes, it's there in Contents/Resources.

**Comment by Lord-Kamina** [comment]
Can you try opening it once manually and then try again to see if you get the same error?

**Comment by Woundorf** [comment]
After opening it once manually it now lets me add a custom scheme without error.

**Comment by Lord-Kamina** [comment]
I'll see tonight if I can do something to fix this.

**Comment by Woundorf** [comment]
Ok, thanks for your help.

**Comment by wenchunl** [comment]
I download the release version, and try to add JNLP protocol , and get the same error. My version is also 10.13.6. Would you please give some advise about how to register the JNLP protocol along with java web start?  I want that something like jnlp://myweb.com:7777/launcher.jnlp?Id=17846 to be opened, and launch the specified native application. Thanks in advance.

**Comment by wenchunl** [comment]
I also notice that you marked this has workaround label, and wonder that what's the workaround?

**Comment by Lord-Kamina** [comment]
@wenchunl the solution is literally 4 posts above yours...

**Comment by wenchunl** [comment]
@Lord-Kamina  you mean this `After opening it once manually it now lets me add a custom scheme without error.`?  but how to do that "manually"? And I can't find the `Contents/Resources.`, I can just launch your app from System->Preferences

**Comment by Lord-Kamina** [comment]
Yes, that; you have to find the prefpane where it's installed (most likely either `~/Library/PreferencePanes` or `/Library/PreferencePanes`) and Ctrl+Click -> Show Package Contents.

**Comment by wenchunl** [comment]
Thank you for hint. I can find the package contents now, but when I try to open that application, the application just terminated. Would you please give me more advise? I don't know what should to do next step. 

<img width="903" alt="Screen Shot 2019-03-15 at 1 15 01 PM" src="https://user-images.githubusercontent.com/24265305/54410003-9377af80-4724-11e9-8b95-cbe74647c8c0.png">

**Comment by Lord-Kamina** [comment]
You're supposed to open it by double clicking the .app and anyway it's not supposed to do anything (isn't the name a hint?). It's primary purpose is to disable file associations but it's also needed in order to register new URL schemes.

**Comment by wenchunl** [comment]
Thanks for clarify.
So, what you mean is that to launch the SwiftDefaultApp after that ? I want to register the jnlp protocol, would you please give some guidance on how to accomplish this?

**Comment by Lord-Kamina** [comment]
It gives an error that it can't find ThisAppDoesNothing.app, that happens because said app had never been launched. After it's launched once, Launch Services should find it and adding the scheme should work.

**Comment by wenchunl** [comment]
I launched the SwiftDefaultApp, and from the Application perspective, I checked the jnlp with javawsLauncher, and now it works.  But I wonder another thing that after I uninstall the app, the protocol is still be registered,  how can I unregister that? (I believe the file `com.apple.launchservice.secure.plist` under `~/Library/Preferences/com.apple.LaunchServices` has been modified, but I don't know how to restore it to default settings)

**Comment by Lord-Kamina** [comment]
LaunchServices is being constantly maintained and cleaned. If you delete an app registered as default for a scheme, the association will most likely disappear eventually.

**Comment by jpawlowski** [comment]
Opening ThisAppDoesNothing.app manually will also fail like this:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/75446/56137673-a5ec3f80-5f95-11e9-869a-61053cb79a5a.png">

Manual overwrite is required:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/75446/56137738-c1efe100-5f95-11e9-94d7-5d6e6d5b6d55.png">

Afterwards, everything will be okay.
So, maybe the original issue is that this piggyback app is not signed?

**Comment by Lord-Kamina** [comment]
> So, maybe the original issue is that this piggyback app is not signed?

That it is, but the failing could still be handled more gracefully 

> Opening ThisAppDoesNothing.app manually will also fail like this:

That is why I recommended opening it via Ctrl+Click -> Open, as that usually is interpreted to override Gatekeeper.
